import { LayoutDashboard } from "lucide-react";
import type { ModuleDefinition } from "@/types";

export const dashboardModule: ModuleDefinition = {
  id: "dashboard",
  permissions: ["dashboard:view"],
  nav: [
    {
      id: "dashboard",
      href: "/dashboard",
      labelKey: "nav.dashboard",
      icon: LayoutDashboard,
      order: 1,
      permissions: ["dashboard:view"],
    },
  ],
  routes: [{ path: "/dashboard", labelKey: "nav.dashboard" }],
  commands: [
    {
      id: "go-dashboard",
      labelKey: "command.goDashboard",
      href: "/dashboard",
      group: "pages",
      icon: LayoutDashboard,
      keywords: ["dashboard", "home", "داشبورد"],
      permissions: ["dashboard:view"],
    },
  ],
  widgets: [
    {
      id: "revenue",
      component: "RevenueWidget",
      colSpan: 7,
      rowSpan: 2,
      order: 1,
      permissions: ["dashboard:view"],
    },
    {
      id: "sales",
      component: "SalesWidget",
      colSpan: 5,
      order: 2,
      permissions: ["dashboard:view"],
    },
    {
      id: "visitors",
      component: "VisitorsWidget",
      colSpan: 5,
      order: 3,
      permissions: ["dashboard:view"],
    },
    {
      id: "orders",
      component: "OrdersWidget",
      colSpan: 7,
      rowSpan: 2,
      order: 4,
      permissions: ["orders:view"],
    },
    {
      id: "activity",
      component: "ActivityWidget",
      colSpan: 5,
      rowSpan: 2,
      order: 5,
      permissions: ["dashboard:view"],
    },
    {
      id: "calendar",
      component: "CalendarWidget",
      colSpan: 5,
      rowSpan: 2,
      order: 6,
      permissions: ["dashboard:view"],
    },
    {
      id: "tasks",
      component: "TasksWidget",
      colSpan: 4,
      rowSpan: 2,
      order: 7,
      permissions: ["dashboard:view"],
    },
    {
      id: "quick-actions",
      component: "QuickActionsWidget",
      colSpan: 4,
      order: 8,
      permissions: ["dashboard:view"],
    },
    {
      id: "notifications",
      component: "NotificationsWidget",
      colSpan: 4,
      rowSpan: 2,
      order: 9,
      permissions: ["dashboard:view"],
    },
    {
      id: "storage",
      component: "StorageWidget",
      colSpan: 3,
      order: 10,
      permissions: ["dashboard:view"],
    },
    {
      id: "traffic",
      component: "TrafficWidget",
      colSpan: 5,
      order: 11,
      permissions: ["dashboard:view"],
    },
    {
      id: "payments",
      component: "PaymentsWidget",
      colSpan: 7,
      order: 12,
      permissions: ["dashboard:view"],
    },
  ],
};
