import {
  AlertCircle,
  Box,
  CircleDot,
  FormInput,
  KeyRound,
  LayoutTemplate,
  LockKeyhole,
  MailQuestion,
  RectangleEllipsis,
  ToggleLeft,
  UserPlus,
  CaseSensitive,
  BadgeCheck,
  ListChecks,
  PanelsTopLeft,
  MousePointerClick,
} from "lucide-react";
import type { ModuleDefinition } from "@/types";

export const showcaseModule: ModuleDefinition = {
  id: "showcase",
  permissions: ["showcase:view"],
  nav: [
    {
      id: "showcase-auth",
      href: "/showcase/auth",
      labelKey: "nav.showcaseAuth",
      icon: KeyRound,
      order: 90,
      permissions: ["showcase:view"],
      children: [
        {
          id: "auth-login-simple",
          href: "/showcase/auth/login-simple",
          labelKey: "nav.authLoginSimple",
          icon: CircleDot,
          permissions: ["showcase:view"],
        },
        {
          id: "auth-login-side",
          href: "/showcase/auth/login-side",
          labelKey: "nav.authLoginSide",
          icon: CircleDot,
          permissions: ["showcase:view"],
        },
        {
          id: "auth-login-split",
          href: "/showcase/auth/login-split",
          labelKey: "nav.authLoginSplit",
          icon: CircleDot,
          permissions: ["showcase:view"],
        },
        {
          id: "auth-register",
          href: "/showcase/auth/register",
          labelKey: "nav.authRegister",
          icon: UserPlus,
          permissions: ["showcase:view"],
        },
        {
          id: "auth-forgot",
          href: "/showcase/auth/forgot-password",
          labelKey: "nav.authForgot",
          icon: MailQuestion,
          permissions: ["showcase:view"],
        },
        {
          id: "auth-reset",
          href: "/showcase/auth/reset-password",
          labelKey: "nav.authReset",
          icon: LockKeyhole,
          permissions: ["showcase:view"],
        },
        {
          id: "auth-otp",
          href: "/showcase/auth/otp",
          labelKey: "nav.authOtp",
          icon: RectangleEllipsis,
          permissions: ["showcase:view"],
        },
      ],
    },
    {
      id: "showcase-components",
      href: "/showcase/components",
      labelKey: "nav.showcaseComponents",
      icon: Box,
      order: 91,
      permissions: ["showcase:view"],
      children: [
        {
          id: "comp-button",
          href: "/showcase/components/button",
          labelKey: "nav.compButton",
          icon: MousePointerClick,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-input",
          href: "/showcase/components/input",
          labelKey: "nav.compInput",
          icon: FormInput,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-switch",
          href: "/showcase/components/switch",
          labelKey: "nav.compSwitch",
          icon: ToggleLeft,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-checkbox",
          href: "/showcase/components/checkbox",
          labelKey: "nav.compCheckbox",
          icon: ListChecks,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-radio",
          href: "/showcase/components/radio",
          labelKey: "nav.compRadio",
          icon: CircleDot,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-select",
          href: "/showcase/components/select",
          labelKey: "nav.compSelect",
          icon: LayoutTemplate,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-textarea",
          href: "/showcase/components/textarea",
          labelKey: "nav.compTextarea",
          icon: CaseSensitive,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-badge",
          href: "/showcase/components/badge",
          labelKey: "nav.compBadge",
          icon: BadgeCheck,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-alert",
          href: "/showcase/components/alert",
          labelKey: "nav.compAlert",
          icon: AlertCircle,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-tabs",
          href: "/showcase/components/tabs",
          labelKey: "nav.compTabs",
          icon: PanelsTopLeft,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-map",
          href: "/showcase/components/map",
          labelKey: "nav.compMap",
          icon: LayoutTemplate,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-charts",
          href: "/showcase/components/charts",
          labelKey: "nav.compCharts",
          icon: PanelsTopLeft,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-forms",
          href: "/showcase/components/forms",
          labelKey: "nav.compForms",
          icon: FormInput,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-slider",
          href: "/showcase/components/slider",
          labelKey: "nav.compSlider",
          icon: ToggleLeft,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-table",
          href: "/showcase/components/table",
          labelKey: "nav.compTable",
          icon: ListChecks,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-skeleton",
          href: "/showcase/components/skeleton",
          labelKey: "nav.compSkeleton",
          icon: Box,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-datetime",
          href: "/showcase/components/datetime",
          labelKey: "nav.compDatetime",
          icon: LayoutTemplate,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-cards",
          href: "/showcase/components/cards",
          labelKey: "nav.compCards",
          icon: BadgeCheck,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-modal",
          href: "/showcase/components/modal",
          labelKey: "nav.compModal",
          icon: AlertCircle,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-dropdown",
          href: "/showcase/components/dropdown",
          labelKey: "nav.compDropdown",
          icon: MousePointerClick,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-file-upload",
          href: "/showcase/components/file-upload",
          labelKey: "nav.compFileUpload",
          icon: FormInput,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-validation",
          href: "/showcase/components/validation",
          labelKey: "nav.compValidation",
          icon: ListChecks,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-rich-text",
          href: "/showcase/components/rich-text",
          labelKey: "nav.compRichText",
          icon: CaseSensitive,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-tooltip",
          href: "/showcase/components/tooltip",
          labelKey: "nav.compTooltip",
          icon: MousePointerClick,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-drawer",
          href: "/showcase/components/drawer",
          labelKey: "nav.compDrawer",
          icon: LayoutTemplate,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-carousel",
          href: "/showcase/components/carousel",
          labelKey: "nav.compCarousel",
          icon: PanelsTopLeft,
          permissions: ["showcase:view"],
        },
        {
          id: "comp-hooks",
          href: "/showcase/components/hooks",
          labelKey: "nav.compHooks",
          icon: ToggleLeft,
          permissions: ["showcase:view"],
        },
      ],
    },
  ],
  routes: [
    { path: "/showcase", labelKey: "nav.showcase" },
    { path: "/showcase/auth/login-simple", labelKey: "nav.authLoginSimple" },
    { path: "/showcase/components/button", labelKey: "nav.compButton" },
  ],
  commands: [
    {
      id: "go-showcase",
      labelKey: "command.goShowcase",
      href: "/showcase",
      group: "pages",
      icon: Box,
      keywords: ["showcase", "ui", "components", "auth", "نمایش"],
      permissions: ["showcase:view"],
    },
  ],
};
